# Generated by Django 2.2.14 on 2020-07-06 06:50

from django.db import migrations, models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filee',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Files', validators=[uploads.validators.validate_file_size]),
        ),
    ]
